version: "3"

services:
  rails:
    build: .
    image: calvincaulfield/drama
    ports:
      - 3000:3000
    restart: always
    environment:
      - DB_DATABASE=something
    env_file:
      - env/.env-stage
