version: "3"

services:
  rails:
    build: .
    image: calvincaulfield/drama
    ports:
      - 3000:3000
    command: bash -f ./start_docker.sh

    network_mode: host
    restart: always
    environment:
      - RAILS_ENV=production
      - DB_HOST
      - DB_USER
      - DB_PORT
      - DB_PASSWD
      - DRAMA_PORT
      - SECRET_KEY_BASE
      - RAILS_SERVE_STATIC_FILES

