version: '3'

services:
  rails:
    image: calvincaulfield/drama
    env_file:
      - ../.env
    environment:
      - DB_DATABASE=something
    ports:
      - "3000:3000"
    network_mode: "host"
    restart: always


