version: '3'

services:
  rails:
    build: .
    image: calvincaulfield/drama
    ports:
      - 3000:3000
    network_mode: "host"
    restart: always
    environment:
      - DB_DATABASE=something
    env_file:
      - ../.env-docker


